# Discussion

Citizen science data has many challenges, especially spatial bias and temporal bias (Johnston et al.). Users are limited by access to areas in order to make observations. Temporal assumes that the user submitting the observation made a correct identification of the species. While eBird and GBIF have QC protocols which require volunteers to monitor submissions (Johnston et al.), it is difficult to know the reality of the observer and observation. Limitations are when submissions of a species are within range, there is no prompt for reconsideration by a volunteer on eBird. Another large challenge to citizen science data is class imbalance because there will be more non-detection's than actual detection's (Johnston et al.). With bias' and imbalances reliable inferences on the data become a great challenge for data scientists (Johnston et al.).

In the future, incorporating non-detection's to predict presence could strengthen the results of this analysis. While we know from this data set that there is a species detection at this site, non-detection could significantly outweigh an actual detection, rendering one single detection rare or uncommon. This could alter the outcome of environmental characteristic preferences in the analysis, skewing the data to prefer areas that do not normally contain Dippers.

It is worth noting that land cover dominance throughout Dipper range can and will occur. For example the land cover dominance in Colorado compared to Washington, differ due to climate. While the comparison in this analysis is with Sullivan and Vierlings 2012 study, Idaho and Colorado have similar climactic attributes which can help validate the analysis.

Slope being an important attribute to dipper presence could have been analyzed more efficiently. In the future, pulling a specific slope attribute from the Dipper observation could have yielded more accurate results compared to the outcome from average slope calculation in the NHD data set. While our analysis is contrary to the literature, it is worth noting that the average slope of streams during breeding and non breeding has some significance. This could raise the question for whether streams with an average slope percentage that is higher has less the volume of water in the non breeding season, improving hunting success throughout the winter. However, this was not explored throughout this research.
